# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure for Students'
    subscriptionId: 'e8f789fe-e545-4fdd-bfd2-f38cb5d5c73d'
    action: 'Create Or Update Resource Group'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    csmFile: 'quickstarts/microsoft.storage/storage-account-create/azuredeploy.json'
    csmParametersFile: 'quickstarts/microsoft.storage/storage-account-create/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
